default:
  interruptible: true
  image: node:lts-alpine
install:
  stage: dependencies
  script:
    # Install dependencies
    - npm install @angular/cli --prefer-offline
    - npm install --prefer-offline
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules

stages:
  - test
  - build
  - deploy

lint:
  stage: quality
  needs: ['install']
  script:
    - ng lint
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules
    policy: pull
